name:        mega-sdist
version:     0.4.3.1
synopsis:    Handles uploading to Hackage from mega repos
description: Please see the description on Github at <https://github.com/snoyberg/mega-sdist#readme>
category:    Distribution
author:      Michael Snoyman
maintainer:  michael@snoyman.com
license:     MIT
github:      snoyberg/mega-sdist

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >=4 && <5
- bytestring
- optparse-simple
- pantry >= 0.6
- path
- path-io
- rio
- rio-orphans
- yaml
- aeson

executables:
  mega-sdist:
    main: mega-sdist.hs
    ghc-options: -threaded -with-rtsopts=-N
